name: Deploy to EC2 K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy to K3s
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            kubectl apply -f ~/new_project/k8s/configmap.yaml
            kubectl apply -f ~/new_project/k8s/deployment.yaml
            kubectl apply -f ~/new_project/k8s/service.yaml
